services:

  db:
    build: ./DB
    container_name: Our_DB
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h localhost"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 30s

  backend:
    build: ./backend
    container_name: BE
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: inventory
    depends_on:
      db:
        condition: service_healthy
      alert_service:
        condition: service_started
      reporting_service:
        condition: service_started
    ports:
      - "5000:5000"
    restart: unless-stopped

  alert_service:
    build: ./alert-service
    container_name: Alert_Service
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: inventory
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5001:5001"
    restart: unless-stopped

  reporting_service:
    build: ./reporting-service
    container_name: Reporting_Service
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: inventory
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5002:5002"
    restart: unless-stopped

  nginx:
    build: ./FrontEnd
    container_name: FE
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped


volumes:
  pg_data:
