apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kubernetes/backend-servicemonitor.yaml
  - kubernetes/postgres-exporter.yaml
  - kubernetes/postgres-servicemonitor.yaml
  - kubernetes/backend-alert-rules.yaml
  - kubernetes/postgres-alert-rules.yaml
  - kubernetes/grafana-ingress.yaml

configMapGenerator:
  - name: smart-inventory-grafana-dashboard
    files:
      - smart-inventory-overview.json=grafana/dashboards/smart-inventory-overview.json
    options:
      labels:
        grafana_dashboard: "1"

generatorOptions:
  disableNameSuffixHash: true
